/*
 * This file is generated by jOOQ.
 */
package models.db.test_schema.students;


import models.db.test_schema.students.tables.Students;


/**
 * Convenience access to all tables in test_schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_schema.students</code>.
     */
    public static final Students STUDENTS = Students.STUDENTS;
}
