/*
 * This file is generated by jOOQ.
 */
package models.db.test_schema.students;


import java.util.Arrays;
import java.util.List;

import models.db.test_schema.students.tables.Students;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_schema</code>
     */
    public static final TestSchema TEST_SCHEMA = new TestSchema();

    /**
     * The table <code>test_schema.students</code>.
     */
    public final Students STUDENTS = Students.STUDENTS;

    /**
     * No further instances allowed
     */
    private TestSchema() {
        super("test_schema", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Students.STUDENTS
        );
    }
}
